apiVersion: v1
kind: ConfigMap
metadata:
  name: pihole-adlists
  namespace: pihole-system
data:
  adlists.list: |
    https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADhosts_without_controversies.txt
    https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Spam/hosts
    https://v.firebog.net/hosts/static/w3kbl.txt
    https://v.firebog.net/hosts/BillStearns.txt
    https://sysctl.org/cameleon/hosts
    https://www.dshield.org/feeds/suspiciousdomains_Low.txt
    https://www.dshield.org/feeds/suspiciousdomains_Medium.txt
    https://www.dshield.org/feeds/suspiciousdomains_High.txt
    https://raw.githubusercontent.com/matomo-org/referrer-spam-blacklist/master/spammers.txt
    https://hostsfile.org/Downloads/hosts.txt
    https://someonewhocares.org/hosts/zero/hosts
    https://raw.githubusercontent.com/vokins/yhosts/master/hosts
    https://winhelp2002.mvps.org/hosts.txt
    https://hosts.nfz.moe/basic/hosts
    https://raw.githubusercontent.com/RooneyMcNibNug/pihole-stuff/master/SNAFU.txt
    https://ssl.bblck.me/blacklists/hosts-file.txt
    https://hostsfile.mine.nu/hosts0.txt
    https://www.joewein.net/dl/bl/dom-bl-base.txt
    https://v.firebog.net/hosts/Kowabit.txt
    https://adblock.mahakala.is
    https://adaway.org/hosts.txt
    https://v.firebog.net/hosts/AdguardDNS.txt
    https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt
    https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
    https://v.firebog.net/hosts/Easylist.txt
    https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext
    https://raw.githubusercontent.com/FadeMind/hosts.extras/master/UncheckyAds/hosts
    https://raw.githubusercontent.com/bigdargon/hostsVN/master/hosts
    https://raw.githubusercontent.com/jdlingyu/ad-wars/master/hosts
    https://v.firebog.net/hosts/Easyprivacy.txt
    https://v.firebog.net/hosts/Prigent-Ads.txt
    https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-blocklist.txt
    https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.2o7Net/hosts
    https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt
    https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt
    https://hostfiles.frogeye.fr/firstparty-trackers-hosts.txt
    https://raw.githubusercontent.com/InnoScorpio/W3C_annual_most_used_survey_blocklist/master/Top500_Domains.txt
    https://hostfiles.frogeye.fr/multiparty-trackers-hosts.txt
    https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/android-tracking.txt
    https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/SmartTV.txt
    https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/AmazonFireTV.txt
    https://v.firebog.net/hosts/Airelle-trc.txt
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt
    https://osint.digitalside.it/Threat-Intel/lists/latestdomains.txt
    https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt
    https://mirror1.malwaredomains.com/files/justdomains
    https://v.firebog.net/hosts/Prigent-Malware.txt
    https://mirror.cedia.org.ec/malwaredomains/immortal_domains.txt
    https://www.malwaredomainlist.com/hostslist/hosts.txt
    https://bitbucket.org/ethanr/dns-blacklists/raw/8575c9f96e5b4a1308f2f12394abd86d0927a4a0/bad_lists/Mandiant_APT1_Report_Appendix_D.txt
    https://phishing.army/download/phishing_army_blocklist_extended.txt
    https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-malware.txt
    https://v.firebog.net/hosts/Shalla-mal.txt
    https://raw.githubusercontent.com/Spam404/lists/master/main-blacklist.txt
    https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Risk/hosts
    https://urlhaus.abuse.ch/downloads/hostfile/
    https://raw.githubusercontent.com/HorusTeknoloji/TR-PhishingList/master/url-lists.txt
    https://v.firebog.net/hosts/Airelle-hrsk.txt
    https://zerodot1.gitlab.io/CoinBlockerLists/hosts_browser
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pihole-regex
  namespace: pihole-system
data:
  regex.list: |
    ^(.+[-_.])??adse?rv(er?|ice)?s?[0-9]*[-.]
    ^(.+[-_.])??m?ad[sxv]?[0-9]*[-_.]
    ^(.+[-_.])??telemetry[-.]
    ^(.+[-_.])??xn--
    ^adim(age|g)s?[0-9]*[-_.]
    ^adtrack(er|ing)?[0-9]*[-.]
    ^advert(s|is(ing|ements?))?[0-9]*[-_.]
    ^aff(iliat(es?|ion))?[-.]
    ^analytics?[-.]
    ^banners?[-.]
    ^beacons?[0-9]*[-.]
    ^count(ers?)?[0-9]*[-.]
    ^pixels?[-.]
    ^stat(s|istics)?[0-9]*[-.]
    ^track(ers?|ing)?[0-9]*[-.]
    ^traff(ic)?[-.]
    ^(.*)\.g00\.(.*)
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pihole-env
  namespace: pihole-system
data:
  TZ: UTC
  DNS1: 127.0.0.1#5054
  DNS2: 127.0.0.1#5054
